# -*- coding: utf-8 -*-
"""codelab 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQN7aCKWbEP5TEsimP-MkKujuS028a_J

# MERFISH Cell-Type Classification — Codelab

Companion notebook for **Project 3 Part 2** (Cell Type Classification CS-GY 9223).


| Stage | Methods |
|---|---|
| Segmentation | Cellpose 3 · SAM · SAM 3 · DINOv3 |
| Cell-type classification | scVI / scANVI · CellTypist · Hierarchical XGBoost |
| Spatial | Squidpy + small GCN |

**Mini dataset (~63 MB tarball):**
- 2 train FOVs (`FOV_160`, `FOV_107`) — max class diversity
- 1 held-out FOV (`FOV_122`) — for in-notebook ARI scoring
- 1 real test FOV (`FOV_E`) — no GT, inference demo
- Middle-z DAPI + polyT only

**Runtime:** GPU recommended (Colab T4 is enough).

## What we're predicting

For every decoded mRNA spot in a test FOV, output **4 hierarchical cell-type labels** (Allen ABCA-4 taxonomy):

```
spot_id, fov, class, subclass, supertype, cluster
```

Plus `background` for spots that fall outside any cell or in cells too noisy to classify.

**Metric:** mean ARI across 40 values = 10 test FOVs × 4 hierarchy levels. ARI is permutation-invariant — only spot pair groupings matter, not the label strings.

## Mini pipeline overview

Every method below plugs into the same **uniform pipeline**, scored on FOV_122:

```
DAPI + polyT image (2048×2048)
        │
        ▼
┌─────────────────────┐
│  1. Segmentation    │   Cellpose / SAM / DINOv3  →  int mask, 0 = background
└─────────────────────┘
        │ mask[row, col]
        ▼
┌─────────────────────┐
│  2. Spot → cell     │   each spot inherits its mask cell-id
└─────────────────────┘
        │ aggregate target_gene per cell
        ▼
┌─────────────────────┐
│  3. Cell × gene     │   per-cell expression vector (length 1147 genes)
│     count matrix    │
└─────────────────────┘
        │ train on labeled cells (counts.h5ad, 4-level GT)
        ▼
┌─────────────────────┐
│  4. Classification  │   scVI · CellTypist · HierXGB  →  4 labels per cell
└─────────────────────┘
        │ broadcast cell label → all its spots
        ▼
┌─────────────────────┐
│  5. Project to      │   mask == 0 spots  →  'background' at all 4 levels
│     spots           │
└─────────────────────┘
        │
        ▼
   per-spot 4-level prediction  →  ARI vs GT
```

**Inputs**
- *Image*: DAPI + polyT middle-z plane per FOV (2048×2048, uint16)
- *Spots*: `(spot_id, image_row, image_col, target_gene)` — gene already decoded
- *Training labels*: `counts.h5ad` — labeled cells × 1147 genes, with class/subclass/supertype/cluster per cell

**What each stage decides**
- *Segmentation* sets **which spots count as belonging to a cell** (the dominant error source — Cellpose-cyto3 over-segments 3× vs Allen GT)
- *Classification* sets **which cell type each cell gets** (data-limited on the mini set — ceiling ~±0.03 ARI; real Phase 2 has 5230 cells and clears 0.35)
- *Background* assignment is a real prediction, not a fallback — ~87% of spots are extracellular and getting them right counts toward ARI
"""

# Install gdown for downloading from Google Drive
!pip install gdown

import gdown
import tarfile
import os

# Google Drive file ID for merfish_mini.tar.gz
file_id = '1mrBTlf-UqqCP2ctQLXvGo9lS_i9gcAlW'
output_filename = 'merfish_mini.tar.gz'

print(f"Downloading {output_filename} from Google Drive (ID: {file_id})...")

try:
    gdown.download(id=file_id, output=output_filename, quiet=False)
    print(f"Download complete: {output_filename}")

    # Extract the contents of the tar.gz file
    print(f"Extracting {output_filename}...")
    with tarfile.open(output_filename, 'r:gz') as tar:
        tar.extractall()
    print("Extraction complete.")

except Exception as e:
    print(f"An error occurred during download or extraction: {e}")

# List the contents of the current directory to verify extraction
print("Contents of the current directory after extraction:")
!ls -F

# Light dependencies used across sections. Heavier ones (cellpose, sam,
# scvi-tools, celltypist, squidpy, torch-geometric) install per section so
!pip install -q anndata scanpy scikit-image scikit-learn xgboost matplotlib seaborn shapely

import os, tarfile, pathlib
DATA_DIR = pathlib.Path('/content/merfish_mini')

print('Files:')
for p in sorted(DATA_DIR.rglob('*')):
    if p.is_file():
        print(f'  {p.relative_to(DATA_DIR)}  ({p.stat().st_size/1e6:.1f} MB)')

# Restart runtime to ensure changes take effect
import os
os.kill(os.getpid(), 9)

# Fix pandas dependency conflict by downgrading to the version required by google-colab
!pip install pandas==2.2.2

# All utility functions live here so each method section is short.
import json, numpy as np, pandas as pd, anndata as ad
from pathlib import Path
from skimage.draw import polygon as sk_polygon
from sklearn.metrics import adjusted_rand_score

DATA_DIR = Path('/content/merfish_mini')
MANIFEST = json.loads((DATA_DIR / 'manifest.json').read_text())
FOV_META = pd.read_csv(DATA_DIR / 'reference' / 'fov_metadata.csv').set_index('fov')

LEVELS = ['class_label', 'subclass_label', 'supertype_label', 'cluster_label']
PIXEL = 0.109   # µm per pixel (also in fov_metadata.pixel_size)

# --- image loading ---
def load_fov(fov: str):
    '''Return (dapi, polyt) at middle z as 2048x2048 uint16.'''
    data = np.load(DATA_DIR / 'images' / f'{fov}_images.npz')
    return data['dapi'], data['polyt']

# --- µm <-> pixel conversion ---
def um_to_pix(fov: str, x_um, y_um):
    '''Global µm coords -> (row, col) pixel coords inside the 2048x2048 FOV.'''
    ox, oy = FOV_META.loc[fov, ['fov_x', 'fov_y']]
    ps = FOV_META.loc[fov, 'pixel_size']
    col = (np.asarray(x_um) - ox) / ps
    row = (np.asarray(y_um) - oy) / ps
    return row, col

# --- GT mask from polygon boundaries ---
def rasterize_gt_mask(fov: str, z: int = 2) -> tuple[np.ndarray, dict]:
    '''Build a 2048x2048 int mask from cell_boundaries.csv at the given z.
    Returns (mask, id_lookup) where id_lookup[mask_id] = original cell_id.'''
    boundaries = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_boundaries.csv',
                             index_col=0)
    labels = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_labels.csv')
    labels = labels[labels.fov == fov].set_index('cell_id')
    # Only cells whose centroid is in this FOV
    cells_here = boundaries.loc[boundaries.index.astype(str).isin(labels.index.astype(str))]

    mask = np.zeros((2048, 2048), dtype=np.int32)
    id_lookup = {}
    bx_col = f'boundaryX_z{z}'
    by_col = f'boundaryY_z{z}'

    for i, (cid, row) in enumerate(cells_here.iterrows(), start=1):
        xs = row[bx_col]
        ys = row[by_col]
        if pd.isna(xs) or pd.isna(ys):
            continue
        xs = np.array([float(v) for v in str(xs).split(',') if v.strip()])
        ys = np.array([float(v) for v in str(ys).split(',') if v.strip()])
        if len(xs) < 3:
            continue
        r, c = um_to_pix(fov, xs, ys)
        rr, cc = sk_polygon(r, c, shape=mask.shape)
        mask[rr, cc] = i
        id_lookup[i] = str(cid)
    return mask, id_lookup

# --- spots -> cell expression vector ---
GENE_LIST = ad.read_h5ad(DATA_DIR / 'ground_truth' / 'counts.h5ad').var_names.tolist()
GENE_INDEX = {g: i for i, g in enumerate(GENE_LIST)}

def spots_to_cell_counts(mask: np.ndarray, spots: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
    '''Aggregate spots into cell x gene counts using mask[image_row, image_col].
    Returns (counts, cell_ids) where counts is (n_cells, n_genes) and cell_ids
    is the array of mask integer IDs (excluding 0 = background).'''
    rows = spots['image_row'].clip(0, mask.shape[0]-1).astype(int).values
    cols = spots['image_col'].clip(0, mask.shape[1]-1).astype(int).values
    cids = mask[rows, cols]
    keep = cids > 0
    if not keep.any():
        return np.zeros((0, len(GENE_LIST)), dtype=np.int32), np.array([], dtype=np.int32)
    cids = cids[keep]
    genes = spots['target_gene'].values[keep]
    gix = np.array([GENE_INDEX.get(g, -1) for g in genes])
    valid = gix >= 0
    cids, gix = cids[valid], gix[valid]

    unique_ids, inv = np.unique(cids, return_inverse=True)
    counts = np.zeros((len(unique_ids), len(GENE_LIST)), dtype=np.int32)
    np.add.at(counts, (inv, gix), 1)
    return counts, unique_ids

# --- spot-level GT labels for a FOV ---
def gt_spot_labels(fov: str, z: int = 2):
    '''Return spots_df + 4 GT label arrays per spot for the given FOV.
    Spots whose pixel falls in mask==0 get background.'''
    spots = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
    spots = spots[spots.fov == fov].copy().reset_index(drop=True)
    mask, lookup = rasterize_gt_mask(fov, z=z)
    rows = spots['image_row'].clip(0, mask.shape[0]-1).astype(int).values
    cols = spots['image_col'].clip(0, mask.shape[1]-1).astype(int).values
    mask_ids = mask[rows, cols]

    labels = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_labels.csv').set_index('cell_id')
    out = {lvl: np.array(['background'] * len(spots), dtype=object) for lvl in LEVELS}
    for i, mid in enumerate(mask_ids):
        if mid == 0:
            continue
        cid = lookup.get(mid)
        if cid is None or cid not in labels.index:
            continue
        for lvl in LEVELS:
            v = labels.loc[cid, lvl]
            if isinstance(v, pd.Series):
                v = v.iloc[0]
            out[lvl][i] = str(v)
    return spots, out, mask, lookup

# --- spot-level prediction from a (mask, per-cell-label-dict) ---
def project_to_spots(spots: pd.DataFrame, pred_mask: np.ndarray,
                    cell_labels: dict[int, dict[str, str]]) -> dict[str, np.ndarray]:
    '''cell_labels[mask_id][level] -> predicted label string. Spots in mask==0
    get background.'''
    rows = spots['image_row'].clip(0, pred_mask.shape[0]-1).astype(int).values
    cols = spots['image_col'].clip(0, pred_mask.shape[1]-1).astype(int).values
    mids = pred_mask[rows, cols]
    out = {lvl: np.array(['background'] * len(spots), dtype=object) for lvl in LEVELS}
    for i, mid in enumerate(mids):
        if mid <= 0 or mid not in cell_labels:
            continue
        for lvl in LEVELS:
            out[lvl][i] = cell_labels[mid].get(lvl, 'background')
    return out

def score_predictions(gt: dict[str, np.ndarray], pred: dict[str, np.ndarray]) -> dict[str, float]:
    return {lvl: adjusted_rand_score(gt[lvl], pred[lvl]) for lvl in LEVELS}

print('Helpers loaded. Manifest:', MANIFEST)
print('Genes:', len(GENE_LIST))

"""# Data inspection

"""

import matplotlib.pyplot as plt
import seaborn as sns

labels = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_labels.csv')
print(f'Cells: {len(labels)}    FOVs: {labels.fov.unique().tolist()}')
print(f'Classes: {labels.class_label.nunique()}    '
      f'Subclasses: {labels.subclass_label.nunique()}    '
      f'Supertypes: {labels.supertype_label.nunique()}    '
      f'Clusters: {labels.cluster_label.nunique()}')
display(labels.class_label.value_counts())

# Visualize FOV_160 DAPI + polyT
dapi, polyt = load_fov('FOV_160')
fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(dapi, cmap='Blues_r', vmax=np.percentile(dapi, 99))
ax[0].set_title('FOV_160 DAPI (nuclei)')
ax[1].imshow(polyt, cmap='Greens_r', vmax=np.percentile(polyt, 99))
ax[1].set_title('FOV_160 polyT (cytoplasm)')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

"""# GT segmentation overlay for FOV_122 (held-out)

"""

gt_mask_122, gt_lookup_122 = rasterize_gt_mask('FOV_122', z=2)
n_cells_122 = (gt_mask_122 > 0).any(axis=None) and len(gt_lookup_122)
dapi_122, _ = load_fov('FOV_122')

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(dapi_122, cmap='gray', vmax=np.percentile(dapi_122, 99))
ax[0].set_title('FOV_122 DAPI')
ax[1].imshow(gt_mask_122 > 0, cmap='magma')
ax[1].set_title(f'FOV_122 GT cell mask  (n_cells = {n_cells_122})')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

"""# Build the GT spot-level labels for FOV_122 once. Used to score every method.

"""

spots_122, gt_122, gt_mask_122, gt_lookup_122 = gt_spot_labels('FOV_122', z=2)
print(f'FOV_122 spots: {len(spots_122)}')
for lvl in LEVELS:
    n_bg = (gt_122[lvl] == 'background').sum()
    print(f'  {lvl}: {n_bg}/{len(gt_122[lvl])} are background  '
          f'({n_bg/len(gt_122[lvl])*100:.1f}%)')

# Storage for per-method ARI numbers — fills in as we run each section.
RESULTS: dict[str, dict[str, float]] = {}

def evaluate_segmentation(name: str, pred_mask: np.ndarray,
                          cell_classifier, fov: str = 'FOV_122'):
    '''
    pred_mask: (2048, 2048) int — 0=bg, >0=cell id
    cell_classifier(counts: np.ndarray (n_cells, n_genes)) -> list of dicts
        each dict has keys: class_label, subclass_label, supertype_label, cluster_label
    '''
    spots = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
    spots = spots[spots.fov == fov].copy().reset_index(drop=True)
    counts, mask_ids = spots_to_cell_counts(pred_mask, spots)
    if len(mask_ids) == 0:
        print(f'[{name}] no spots assigned — all background prediction')
        preds = {lvl: np.array(['background'] * len(spots)) for lvl in LEVELS}
    else:
        cell_preds = cell_classifier(counts)
        cell_label_map = {int(mid): cell_preds[i] for i, mid in enumerate(mask_ids)}
        preds = project_to_spots(spots, pred_mask, cell_label_map)

    # Reuse cached GT for FOV_122
    if fov == 'FOV_122':
        gt = gt_122
    else:
        _, gt, _, _ = gt_spot_labels(fov)
    ari = score_predictions(gt, preds)
    ari['mean'] = float(np.mean(list(ari.values())))
    RESULTS[name] = ari
    print(f'[{name}]')
    for lvl, v in ari.items():
        print(f'  {lvl:18s} ARI = {v:+.3f}')
    return preds, ari

"""# Cellpose: pretrained nuclei + cytoplasm
Cellpose is the standard generalist segmentation model for fluorescence microscopy. We use the pretrained nuclei model on DAPI and visualize the result.
"""

!pip install --upgrade --force-reinstall -q cellpose

import cellpose.models
print(dir(cellpose.models))

from cellpose.models import CellposeModel
import torch
import matplotlib.pyplot as plt
import numpy as np

# Whole-cell model (cyto3); falls back to cyto2 on older Cellpose installs.
try:
    cp = CellposeModel(gpu=torch.cuda.is_available(), model_type='cyto3')
except Exception:
    cp = CellposeModel(gpu=torch.cuda.is_available(), model_type='cyto2') #cpsam

# Load both channels: DAPI (nuclei) + polyT (cytoplasm/mRNA-rich body).
dapi_122, polyt_122 = load_fov('FOV_122')

# Cellpose expects (H, W, C). channels=[1, 2] -> ch1 (polyT) = cyto, ch2 (DAPI) = nuclei.
img_122 = np.stack([polyt_122, dapi_122], axis=-1)
cp_mask, _, _ = cp.eval(img_122, diameter=None, channels=[1, 2])
cp_mask = cp_mask.astype(np.int32)

fig, ax = plt.subplots(1, 3, figsize=(18, 6))
ax[0].imshow(dapi_122, cmap='gray', vmax=np.percentile(dapi_122, 99))
ax[0].set_title('FOV_122 DAPI')
ax[1].imshow(polyt_122, cmap='gray', vmax=np.percentile(polyt_122, 99))
ax[1].set_title('FOV_122 polyT')
ax[2].imshow(cp_mask, cmap='nipy_spectral')
ax[2].set_title(f'Cellpose cyto3 mask — {cp_mask.max()} cells')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

"""# Score Cellpose with a kNN classifier on aggregated spot counts.

"""

from sklearn.preprocessing import normalize
from sklearn.neighbors import KNeighborsClassifier

# --- 1. Load training cells (FOV_160 + FOV_107) and their hierarchical labels ---
adata = ad.read_h5ad(DATA_DIR / 'ground_truth' / 'counts.h5ad')
train_mask = adata.obs.fov.isin(['FOV_160', 'FOV_107']).values

X_train = adata.X[train_mask]
if hasattr(X_train, 'toarray'):
    X_train = X_train.toarray()
else:
    X_train = np.asarray(X_train)
Xtr = normalize(X_train, norm='l1')   # per-cell counts -> probability vector
ytr = {lvl: adata.obs[lvl].values[train_mask] for lvl in LEVELS}

print(f'Training cells: {len(Xtr)}  '
      f'(classes={len(set(ytr["class_label"]))}, '
      f'clusters={len(set(ytr["cluster_label"]))})')

# --- 2. One kNN per hierarchy level (cosine on L1-normalized counts) ---
knns = {}
for lvl in LEVELS:
    m = KNeighborsClassifier(n_neighbors=5, metric='cosine')
    m.fit(Xtr, ytr[lvl])
    knns[lvl] = m

def knn_classifier(counts):
    """counts: (n_cells, n_genes) int -> list of {level: label} dicts."""
    Xq = normalize(counts.astype(np.float32), norm='l1')
    return [{lvl: knns[lvl].predict(Xq[i:i+1])[0] for lvl in LEVELS}
            for i in range(len(Xq))]

# --- 3. Score using the cyto3 whole-cell mask from the previous step ---
evaluate_segmentation('Cellpose-cyto3+kNN', cp_mask, knn_classifier)

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

# --- 1. Re-derive what each predicted cell actually got labeled as ---
spots_122 = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
spots_122 = spots_122[spots_122.fov == 'FOV_122'].copy().reset_index(drop=True)

cp_counts, cp_ids = spots_to_cell_counts(cp_mask, spots_122)
pred_per_cell = knn_classifier(cp_counts)
pred_cell_labels = {int(cid): pred_per_cell[i] for i, cid in enumerate(cp_ids)}
print(f'Predicted labels for {len(pred_cell_labels)} Cellpose cells')

# --- 2. Build the GT side: per-cell labels keyed by GT mask integer ---
_, gt, gt_mask, gt_lookup = gt_spot_labels('FOV_122', z=2)
labels_df = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_labels.csv').set_index('cell_id')
gt_cell_labels = {}
for mid, cid in gt_lookup.items():
    if cid in labels_df.index:
        row = labels_df.loc[cid]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]
        gt_cell_labels[mid] = {lvl: str(row[lvl]) for lvl in LEVELS}

# --- 3. Color a mask by per-cell label at the chosen level ---
def colorize_by_label(mask, cell_labels, level):
    label_per_id = {mid: lbls.get(level, 'background')
                    for mid, lbls in cell_labels.items()}
    unique_labels = ['background'] + sorted(set(label_per_id.values()) - {'background'})
    label_to_int = {lbl: i for i, lbl in enumerate(unique_labels)}
    out = np.zeros_like(mask, dtype=np.int32)
    for mid, lbl in label_per_id.items():
        out[mask == mid] = label_to_int[lbl]
    cmap = ListedColormap(
        [(0.05, 0.05, 0.05, 1.0)] +
        list(plt.cm.tab20(np.linspace(0, 1, max(len(unique_labels) - 1, 1))))
    )
    return out, cmap, unique_labels

# --- 4. Side-by-side at every level ---
fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    gt_img, gt_cmap, gt_lbls = colorize_by_label(gt_mask, gt_cell_labels, level)
    pr_img, pr_cmap, pr_lbls = colorize_by_label(cp_mask, pred_cell_labels, level)

    axes[0, col].imshow(gt_img, cmap=gt_cmap, interpolation='nearest')
    axes[0, col].set_title(f'GT — {level}\n({len(gt_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    axes[1, col].imshow(pr_img, cmap=pr_cmap, interpolation='nearest')
    axes[1, col].set_title(f'Cellpose+kNN — {level}\n({len(pr_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    for r in range(2):
        axes[r, col].axis('off')

fig.suptitle('FOV_122 — predicted cell types vs ground truth',
              fontsize=16, y=0.98)
plt.show()

# --- 5. Spot-level scatter (denser, includes the background spots) ---
pred_spot = project_to_spots(spots_122, cp_mask, pred_cell_labels)

fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    for row, (labels, title) in enumerate([(gt[level], 'GT'),
                                            (pred_spot[level], 'Cellpose+kNN')]):
        unique = ['background'] + sorted(set(labels) - {'background'})
        cmap_arr = [(0.92, 0.92, 0.92, 0.4)] + [plt.cm.tab20(i % 20) for i in range(len(unique)-1)]
        lbl_to_i = {l: i for i, l in enumerate(unique)}
        c = [cmap_arr[lbl_to_i[l]] for l in labels]
        axes[row, col].scatter(spots_122['image_col'], spots_122['image_row'],
                                c=c, s=1, linewidths=0)
        axes[row, col].set_xlim(0, 2048)
        axes[row, col].set_ylim(2048, 0)
        axes[row, col].set_aspect('equal')
        axes[row, col].set_title(f'{title} — {level}',
                                  fontsize=12, pad=12,
                                  bbox=dict(facecolor='white', edgecolor='none', pad=3))
        axes[row, col].axis('off')

fig.suptitle('FOV_122 — spot-level predictions vs ground truth',
              fontsize=16, y=0.98)
plt.show()

"""#Fine-tune Cellpose on FOV_160 + FOV_107 GT polygons                                                                                                                                            
    
"""

from cellpose import train as cp_train
from cellpose.models import CellposeModel
import torch, numpy as np

# --- 1. Build training pairs: (image, GT mask) for each of the 2 train FOVs ---
train_imgs, train_masks = [], []
for fov in ['FOV_160', 'FOV_107']:
    dapi, polyt = load_fov(fov)
    img = np.stack([polyt, dapi], axis=0).astype(np.float32)   # (C, H, W) for channel_axis=0
    gt_mask, _ = rasterize_gt_mask(fov, z=2)
    train_imgs.append(img)
    train_masks.append(gt_mask.astype(np.int32))
    print(f'{fov}: img {img.shape}, mask {gt_mask.max()} cells')

# --- 2. Fine-tune cpsam (v4 API) ---
cp_ft = CellposeModel(gpu=torch.cuda.is_available(), pretrained_model='cpsam')

cp_train.train_seg(
    cp_ft.net,
    train_data=train_imgs,
    train_labels=train_masks,
    channel_axis=0,
    n_epochs=200,
    learning_rate=5e-5,
    batch_size=2,
    bsize=256,                     # cpsam REQUIRES 256 (default 224 crashes)
    weight_decay=1e-5,
    save_path=None,
    model_name='cpsam_mini_ft',
)

print('Fine-tuning done.')

# --- 3. Inference on FOV_122 with cellprob_threshold sweep ---
img_122 = np.stack([polyt_122, dapi_122], axis=0).astype(np.float32)

best_mask, best_n, best_thr = None, 0, 0.0
for thr in [0.0, -1.0, -3.0, -6.0]:
    m, _, _ = cp_ft.eval(img_122, channel_axis=0, diameter=None,
                          bsize=256, cellprob_threshold=thr)
    n = int(m.max())
    print(f'  cellprob_threshold={thr:>5.1f}  →  {n} cells')
    if n > best_n:
        best_mask, best_n, best_thr = m.astype(np.int32), n, thr

cp_mask_ft = best_mask
print(f'Picked threshold {best_thr} → {best_n} cells (was {cp_mask.max()} for pretrained cyto3)')

# --- 4. Quick visual: pretrained vs fine-tuned masks ---
fig, ax = plt.subplots(1, 3, figsize=(18, 6))
ax[0].imshow(dapi_122, cmap='gray', vmax=np.percentile(dapi_122, 99))
ax[0].set_title('FOV_122 DAPI')
ax[1].imshow(cp_mask, cmap='nipy_spectral')
ax[1].set_title(f'Pretrained cyto3 — {cp_mask.max()} cells')
ax[2].imshow(cp_mask_ft, cmap='nipy_spectral')
ax[2].set_title(f'Fine-tuned cpsam — {cp_mask_ft.max()} cells')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

# ============================================================
# Re-run kNN classifier + visualization with the FINE-TUNED mask
# ============================================================
evaluate_segmentation('CellposeFT+kNN', cp_mask_ft, knn_classifier)

# --- Build per-cell predictions on the fine-tuned mask ---
cp_counts_ft, cp_ids_ft = spots_to_cell_counts(cp_mask_ft, spots_122)
pred_per_cell_ft = knn_classifier(cp_counts_ft)
pred_cell_labels_ft = {int(cid): pred_per_cell_ft[i] for i, cid in enumerate(cp_ids_ft)}
print(f'Predicted labels for {len(pred_cell_labels_ft)} fine-tuned-Cellpose cells')

# --- Side-by-side mask coloring at every level ---
fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    gt_img, gt_cmap, gt_lbls = colorize_by_label(gt_mask, gt_cell_labels, level)
    pr_img, pr_cmap, pr_lbls = colorize_by_label(cp_mask_ft, pred_cell_labels_ft, level)

    axes[0, col].imshow(gt_img, cmap=gt_cmap, interpolation='nearest')
    axes[0, col].set_title(f'GT — {level}\n({len(gt_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    axes[1, col].imshow(pr_img, cmap=pr_cmap, interpolation='nearest')
    axes[1, col].set_title(f'CellposeFT+kNN — {level}\n({len(pr_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    for r in range(2):
        axes[r, col].axis('off')

fig.suptitle('FOV_122 — fine-tuned Cellpose + kNN vs ground truth',
              fontsize=16, y=0.98)
plt.show()

# --- Spot-level scatter ---
pred_spot_ft = project_to_spots(spots_122, cp_mask_ft, pred_cell_labels_ft)

fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    for row, (labels, title) in enumerate([(gt[level], 'GT'),
                                            (pred_spot_ft[level], 'CellposeFT+kNN')]):
        unique = ['background'] + sorted(set(labels) - {'background'})
        cmap_arr = [(0.92, 0.92, 0.92, 0.4)] + [plt.cm.tab20(i % 20) for i in range(len(unique)-1)]
        lbl_to_i = {l: i for i, l in enumerate(unique)}
        c = [cmap_arr[lbl_to_i[l]] for l in labels]
        axes[row, col].scatter(spots_122['image_col'], spots_122['image_row'],
                                c=c, s=1, linewidths=0)
        axes[row, col].set_xlim(0, 2048)
        axes[row, col].set_ylim(2048, 0)
        axes[row, col].set_aspect('equal')
        axes[row, col].set_title(f'{title} — {level}',
                                  fontsize=12, pad=12,
                                  bbox=dict(facecolor='white', edgecolor='none', pad=3))
        axes[row, col].axis('off')

fig.suptitle('FOV_122 — fine-tuned spot-level predictions vs GT',
              fontsize=16, y=0.98)
plt.show()

"""## Segment Anything (SAM, ViT-H)

SAM is Meta's class-agnostic segmenter. With **automatic mask generation**
we get every region; we then filter to nuclei-shaped ones.

Honest caveat: SAM is trained on natural images, not fluorescence microscopy.
On dense MERFISH nuclei it often **over-segments background or merges adjacent
cells**. We include it as a foundation-model baseline.
"""

!pip install -q git+https://github.com/facebookresearch/segment-anything.git
!wget -q -nc https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth -O /content/sam_vit_h.pth

from segment_anything import sam_model_registry, SamAutomaticMaskGenerator

sam = sam_model_registry['vit_h'](checkpoint='/content/sam_vit_h.pth')
sam.to('cuda' if torch.cuda.is_available() else 'cpu')

# SAM expects RGB uint8. Convert DAPI to a 3-channel uint8 image.
def to_rgb_uint8(img):
    v = np.percentile(img, 99)
    x = np.clip(img.astype(np.float32) / max(v, 1) * 255, 0, 255).astype(np.uint8)
    return np.stack([x, x, x], axis=-1)

rgb_122 = to_rgb_uint8(dapi_122)
amg = SamAutomaticMaskGenerator(sam, points_per_side=64, pred_iou_thresh=0.8)
sam_masks = amg.generate(rgb_122)
print(f'SAM produced {len(sam_masks)} candidate masks')

# Build int mask, filtering by area (nuclei are ~50–600 px at 0.109 µm/px).
sam_mask = np.zeros((2048, 2048), dtype=np.int32)
next_id = 1
for m in sorted(sam_masks, key=lambda d: d['area']):
    a = m['area']
    if not (100 < a < 5000):
        continue
    sel = m['segmentation'] & (sam_mask == 0)
    if sel.sum() < 50:
        continue
    sam_mask[sel] = next_id
    next_id += 1
print(f'After filtering: {sam_mask.max()} cells')

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(dapi_122, cmap='gray', vmax=np.percentile(dapi_122, 99))
ax[0].set_title('FOV_122 DAPI')
ax[1].imshow(sam_mask, cmap='nipy_spectral')
ax[1].set_title(f'SAM auto mask (filtered) — {sam_mask.max()} cells')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

evaluate_segmentation('SAM+kNN', sam_mask, knn_classifier)

"""# Visualize SAM+kNN predicted cell types vs GT

"""

# --- Per-cell predictions on the SAM mask ---
sam_counts, sam_ids = spots_to_cell_counts(sam_mask, spots_122)
pred_per_cell_sam = knn_classifier(sam_counts)
pred_cell_labels_sam = {int(cid): pred_per_cell_sam[i] for i, cid in enumerate(sam_ids)}
print(f'Predicted labels for {len(pred_cell_labels_sam)} SAM cells')

# --- Side-by-side mask coloring at every level ---
fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    gt_img, gt_cmap, gt_lbls = colorize_by_label(gt_mask, gt_cell_labels, level)
    pr_img, pr_cmap, pr_lbls = colorize_by_label(sam_mask, pred_cell_labels_sam, level)

    axes[0, col].imshow(gt_img, cmap=gt_cmap, interpolation='nearest')
    axes[0, col].set_title(f'GT — {level}\n({len(gt_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    axes[1, col].imshow(pr_img, cmap=pr_cmap, interpolation='nearest')
    axes[1, col].set_title(f'SAM+kNN — {level}\n({len(pr_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    for r in range(2):
        axes[r, col].axis('off')

fig.suptitle('FOV_122 — SAM + kNN predictions vs ground truth',
              fontsize=16, y=0.98)
plt.show()

# --- Spot-level scatter ---
pred_spot_sam = project_to_spots(spots_122, sam_mask, pred_cell_labels_sam)

fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    for row, (labels, title) in enumerate([(gt[level], 'GT'),
                                            (pred_spot_sam[level], 'SAM+kNN')]):
        unique = ['background'] + sorted(set(labels) - {'background'})
        cmap_arr = [(0.92, 0.92, 0.92, 0.4)] + [plt.cm.tab20(i % 20) for i in range(len(unique)-1)]
        lbl_to_i = {l: i for i, l in enumerate(unique)}
        c = [cmap_arr[lbl_to_i[l]] for l in labels]
        axes[row, col].scatter(spots_122['image_col'], spots_122['image_row'],
                                c=c, s=1, linewidths=0)
        axes[row, col].set_xlim(0, 2048)
        axes[row, col].set_ylim(2048, 0)
        axes[row, col].set_aspect('equal')
        axes[row, col].set_title(f'{title} — {level}',
                                  fontsize=12, pad=12,
                                  bbox=dict(facecolor='white', edgecolor='none', pad=3))
        axes[row, col].axis('off')

fig.suptitle('FOV_122 — SAM spot-level predictions vs ground truth',
              fontsize=16, y=0.98)
plt.show()

"""# CLAHE-enhanced DAPI → peak-prompted SAM (medium-mask pick) + dense AMG fill + 25 px cytoplasm expansion → kNN classify."""

from segment_anything import sam_model_registry, SamAutomaticMaskGenerator, SamPredictor
from sklearn.preprocessing import normalize
from sklearn.neighbors import KNeighborsClassifier
from skimage import exposure
from skimage.feature import peak_local_max
from skimage.segmentation import expand_labels
from scipy.ndimage import gaussian_filter
import torch, numpy as np, pandas as pd, anndata as ad

sam = sam_model_registry['vit_h'](checkpoint='/content/sam_vit_h.pth')
sam.to('cuda' if torch.cuda.is_available() else 'cpu')

# --- 0. Train per-level kNN classifiers from the 147-cell mini training set ---
adata_knn = ad.read_h5ad(DATA_DIR / 'ground_truth' / 'counts.h5ad')
train_mask = adata_knn.obs.fov.isin(['FOV_160', 'FOV_107']).values

X_train = adata_knn.X[train_mask]
if hasattr(X_train, 'toarray'):
    X_train = X_train.toarray()
else:
    X_train = np.asarray(X_train)
Xtr = normalize(X_train, norm='l1')
ytr = {lvl: adata_knn.obs[lvl].values[train_mask] for lvl in LEVELS}

knns = {lvl: KNeighborsClassifier(n_neighbors=5, metric='cosine').fit(Xtr, ytr[lvl])
        for lvl in LEVELS}
print(f'kNN trained on {len(Xtr)} cells '
      f'(clusters={len(set(ytr["cluster_label"]))})')

def knn_classifier(counts):
    Xq = normalize(counts.astype(np.float32), norm='l1')
    return [{lvl: knns[lvl].predict(Xq[i:i+1])[0] for lvl in LEVELS}
            for i in range(len(Xq))]

# --- 1. CLAHE preprocessing ---
def to_rgb_uint8_clahe(img):
    v_lo, v_hi = np.percentile(img, (1, 99))
    x = np.clip((img.astype(np.float32) - v_lo) / max(v_hi - v_lo, 1), 0, 1)
    x = exposure.equalize_adapthist(x, clip_limit=0.02, kernel_size=128)
    return np.stack([(x * 255).astype(np.uint8)] * 3, axis=-1)

rgb_122 = to_rgb_uint8_clahe(dapi_122)

# --- 2. Peak detection — tighter spacing so we get ~1 peak per nucleus ---
smoothed = gaussian_filter(dapi_122.astype(np.float32), sigma=3)
peaks = peak_local_max(
    smoothed,
    min_distance=20,
    threshold_abs=np.percentile(smoothed, 75),
    exclude_border=8,
)
print(f'Found {len(peaks)} DAPI peaks (~1 per nucleus expected)')

# --- 3. Prompted SAM — pick MEDIUM-sized mask, not smallest ---
predictor = SamPredictor(sam)
predictor.set_image(rgb_122)

NUC_MIN, NUC_MAX = 100, 2000
sam_mask = np.zeros((2048, 2048), dtype=np.int32)
next_id = 1

batch = 64
for i in range(0, len(peaks), batch):
    pts = peaks[i:i+batch][:, [1, 0]]
    pts_t = torch.as_tensor(pts, dtype=torch.float32, device=predictor.device)
    pts_t = predictor.transform.apply_coords_torch(pts_t, rgb_122.shape[:2])
    labels_t = torch.ones(len(pts_t), 1, device=predictor.device)
    masks, ious, _ = predictor.predict_torch(
        point_coords=pts_t.unsqueeze(1),
        point_labels=labels_t,
        multimask_output=True,
    )
    masks = masks.cpu().numpy()
    ious = ious.cpu().numpy()
    for j in range(masks.shape[0]):
        best, best_score = None, -1
        for k in range(3):
            m = masks[j, k]
            a = int(m.sum())
            if not (NUC_MIN <= a <= NUC_MAX):
                continue
            if ious[j, k] < 0.5:
                continue
            score = ious[j, k] - abs(np.log(a / 300.0)) * 0.3
            if score > best_score:
                best_score, best = score, m
        if best is None:
            continue
        sel = best & (sam_mask == 0)
        if sel.sum() < 50:
            continue
        sam_mask[sel] = next_id
        next_id += 1
print(f'Prompted SAM: {sam_mask.max()} cells')

# --- 4. AMG fallback for missed regions ---
amg = SamAutomaticMaskGenerator(
    sam,
    points_per_side=96,
    pred_iou_thresh=0.7,
    stability_score_thresh=0.85,
    crop_n_layers=1,
    crop_n_points_downscale_factor=2,
    min_mask_region_area=NUC_MIN,
)
extra = amg.generate(rgb_122)
print(f'AMG produced {len(extra)} extra candidates')
for m in sorted(extra, key=lambda d: d['area']):
    a = m['area']
    if not (NUC_MIN <= a <= NUC_MAX):
        continue
    sel = m['segmentation'] & (sam_mask == 0)
    if sel.sum() < NUC_MIN:
        continue
    sam_mask[sel] = next_id
    next_id += 1
print(f'After AMG fill: {sam_mask.max()} cells')

# --- 5. CRITICAL: expand nuclei into cytoplasm ---
sam_mask = expand_labels(sam_mask, distance=25).astype(np.int32)

# --- 6. Visualize + score ---
fig, ax = plt.subplots(1, 3, figsize=(18, 6))
ax[0].imshow(dapi_122, cmap='gray', vmax=np.percentile(dapi_122, 99))
ax[0].scatter(peaks[:, 1], peaks[:, 0], s=4, c='red')
ax[0].set_title(f'DAPI + {len(peaks)} peaks')
ax[1].imshow(rgb_122[..., 0], cmap='gray')
ax[1].set_title('CLAHE input to SAM')
ax[2].imshow(sam_mask, cmap='nipy_spectral')
ax[2].set_title(f'SAM (prompted+AMG, expanded) — {sam_mask.max()} cells')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

# Sanity: spot hit rate
spots_chk = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
spots_chk = spots_chk[spots_chk.fov == 'FOV_122']
rows_ = spots_chk['image_row'].clip(0, 2047).astype(int).values
cols_ = spots_chk['image_col'].clip(0, 2047).astype(int).values
print(f'{(sam_mask[rows_, cols_] > 0).mean()*100:.1f}% of spots fall inside a cell')

evaluate_segmentation('SAM-prompted-expanded+kNN', sam_mask, knn_classifier)

"""# Visualize SAM-prompted-expanded + kNN predicted cell types vs GT

"""

from matplotlib.colors import ListedColormap

# --- Setup: GT mask, GT labels, spots, color helper ---
spots_122 = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
spots_122 = spots_122[spots_122.fov == 'FOV_122'].copy().reset_index(drop=True)

_, gt, gt_mask, gt_lookup = gt_spot_labels('FOV_122', z=2)
labels_df = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_labels.csv').set_index('cell_id')
gt_cell_labels = {}
for mid, cid in gt_lookup.items():
    if cid in labels_df.index:
        row = labels_df.loc[cid]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]
        gt_cell_labels[mid] = {lvl: str(row[lvl]) for lvl in LEVELS}

def colorize_by_label(mask, cell_labels, level):
    label_per_id = {mid: lbls.get(level, 'background')
                    for mid, lbls in cell_labels.items()}
    unique_labels = ['background'] + sorted(set(label_per_id.values()) - {'background'})
    label_to_int = {lbl: i for i, lbl in enumerate(unique_labels)}
    out = np.zeros_like(mask, dtype=np.int32)
    for mid, lbl in label_per_id.items():
        out[mask == mid] = label_to_int[lbl]
    cmap = ListedColormap(
        [(0.05, 0.05, 0.05, 1.0)] +
        list(plt.cm.tab20(np.linspace(0, 1, max(len(unique_labels) - 1, 1))))
    )
    return out, cmap, unique_labels

# --- Per-cell predictions on the prompted+expanded SAM mask ---
sam_counts2, sam_ids2 = spots_to_cell_counts(sam_mask, spots_122)
pred_per_cell_sam2 = knn_classifier(sam_counts2)
pred_cell_labels_sam2 = {int(cid): pred_per_cell_sam2[i] for i, cid in enumerate(sam_ids2)}
print(f'Predicted labels for {len(pred_cell_labels_sam2)} SAM-prompted-expanded cells')

# --- Side-by-side mask coloring at every level ---
fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    gt_img, gt_cmap, gt_lbls = colorize_by_label(gt_mask, gt_cell_labels, level)
    pr_img, pr_cmap, pr_lbls = colorize_by_label(sam_mask, pred_cell_labels_sam2, level)

    axes[0, col].imshow(gt_img, cmap=gt_cmap, interpolation='nearest')
    axes[0, col].set_title(f'GT — {level}\n({len(gt_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    axes[1, col].imshow(pr_img, cmap=pr_cmap, interpolation='nearest')
    axes[1, col].set_title(f'SAM-prompted-exp+kNN — {level}\n({len(pr_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    for r in range(2):
        axes[r, col].axis('off')

fig.suptitle('FOV_122 — SAM (prompted + expanded) + kNN predictions vs ground truth',
              fontsize=16, y=0.98)
plt.show()

# --- Spot-level scatter ---
pred_spot_sam2 = project_to_spots(spots_122, sam_mask, pred_cell_labels_sam2)

fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    for row, (labels, title) in enumerate([(gt[level], 'GT'),
                                            (pred_spot_sam2[level], 'SAM-prompted-exp+kNN')]):
        unique = ['background'] + sorted(set(labels) - {'background'})
        cmap_arr = [(0.92, 0.92, 0.92, 0.4)] + [plt.cm.tab20(i % 20) for i in range(len(unique)-1)]
        lbl_to_i = {l: i for i, l in enumerate(unique)}
        c = [cmap_arr[lbl_to_i[l]] for l in labels]
        axes[row, col].scatter(spots_122['image_col'], spots_122['image_row'],
                                c=c, s=1, linewidths=0)
        axes[row, col].set_xlim(0, 2048)
        axes[row, col].set_ylim(2048, 0)
        axes[row, col].set_aspect('equal')
        axes[row, col].set_title(f'{title} — {level}',
                                  fontsize=12, pad=12,
                                  bbox=dict(facecolor='white', edgecolor='none', pad=3))
        axes[row, col].axis('off')

fig.suptitle('FOV_122 — SAM-prompted-expanded spot-level predictions vs ground truth',
              fontsize=16, y=0.98)
plt.show()



"""# Box-prompted SAM"""

from segment_anything import sam_model_registry, SamPredictor
from sklearn.preprocessing import normalize
from sklearn.neighbors import KNeighborsClassifier
from skimage import exposure
from skimage.feature import peak_local_max
from skimage.segmentation import expand_labels
from scipy.ndimage import gaussian_filter
import torch, numpy as np, pandas as pd, anndata as ad

sam = sam_model_registry['vit_h'](checkpoint='/content/sam_vit_h.pth')
sam.to('cuda' if torch.cuda.is_available() else 'cpu')

# --- 0. Train per-level kNN classifiers from the 147-cell mini training set ---
adata_knn = ad.read_h5ad(DATA_DIR / 'ground_truth' / 'counts.h5ad')
train_mask = adata_knn.obs.fov.isin(['FOV_160', 'FOV_107']).values

X_train = adata_knn.X[train_mask]
if hasattr(X_train, 'toarray'):
  X_train = X_train.toarray()
else:
  X_train = np.asarray(X_train)
Xtr = normalize(X_train, norm='l1')
ytr = {lvl: adata_knn.obs[lvl].values[train_mask] for lvl in LEVELS}

knns = {lvl: KNeighborsClassifier(n_neighbors=5, metric='cosine').fit(Xtr, ytr[lvl])
      for lvl in LEVELS}
print(f'kNN trained on {len(Xtr)} cells '
    f'(clusters={len(set(ytr["cluster_label"]))})')

def knn_classifier(counts):
  Xq = normalize(counts.astype(np.float32), norm='l1')
  return [{lvl: knns[lvl].predict(Xq[i:i+1])[0] for lvl in LEVELS}
          for i in range(len(Xq))]

# --- 1. CLAHE ---
def to_rgb_clahe(img):
  v_lo, v_hi = np.percentile(img, (1, 99))
  x = np.clip((img.astype(np.float32) - v_lo) / max(v_hi - v_lo, 1), 0, 1)
  x = exposure.equalize_adapthist(x, clip_limit=0.02, kernel_size=128)
  return np.stack([(x * 255).astype(np.uint8)] * 3, axis=-1)

rgb_122 = to_rgb_clahe(dapi_122)
predictor = SamPredictor(sam)
predictor.set_image(rgb_122)

# --- 2. Detect nuclei centers ---
smoothed = gaussian_filter(dapi_122.astype(np.float32), sigma=3)
peaks = peak_local_max(smoothed, min_distance=20,
                      threshold_abs=np.percentile(smoothed, 75),
                      exclude_border=8)
print(f'Peaks: {len(peaks)}')

# --- 3. Build a tight bounding box around each peak (~6 µm = 55 px on each side) ---
HALF = 28
boxes = np.array([[max(0, x - HALF), max(0, y - HALF),
                  min(2048, x + HALF), min(2048, y + HALF)]
                for y, x in peaks], dtype=np.float32)

# --- 4. Run SAM with box prompts in batches ---
sam_mask = np.zeros((2048, 2048), dtype=np.int32)
next_id = 1
for i in range(0, len(boxes), 64):
  bb = torch.as_tensor(boxes[i:i+64], device=predictor.device)
  bb_t = predictor.transform.apply_boxes_torch(bb, rgb_122.shape[:2])
  masks, ious, _ = predictor.predict_torch(
      point_coords=None, point_labels=None,
      boxes=bb_t,
      multimask_output=False,         # box prompt → 1 unambiguous mask
  )
  masks = masks.cpu().numpy()[:, 0]
  for m, iou in zip(masks, ious.cpu().numpy()):
      a = int(m.sum())
      if not (80 <= a <= 2500): continue
      if iou < 0.5: continue
      sel = m & (sam_mask == 0)
      if sel.sum() < 50: continue
      sam_mask[sel] = next_id; next_id += 1

print(f'Box-prompted SAM: {sam_mask.max()} cells')
sam_mask = expand_labels(sam_mask, distance=25).astype(np.int32)

# --- 5. Sanity: spot hit rate ---
spots_chk = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
spots_chk = spots_chk[spots_chk.fov == 'FOV_122']
rows_ = spots_chk['image_row'].clip(0, 2047).astype(int).values
cols_ = spots_chk['image_col'].clip(0, 2047).astype(int).values
print(f'{(sam_mask[rows_, cols_] > 0).mean()*100:.1f}% spots inside a cell')

# --- 6. Visualize + score ---
fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(dapi_122, cmap='gray', vmax=np.percentile(dapi_122, 99))
ax[0].scatter(peaks[:, 1], peaks[:, 0], s=3, c='red')
ax[0].set_title(f'DAPI + {len(peaks)} peaks')
ax[1].imshow(sam_mask, cmap='nipy_spectral')
ax[1].set_title(f'SAM box-prompted (expanded) — {sam_mask.max()} cells')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

evaluate_segmentation('SAM-box+kNN', sam_mask, knn_classifier)

from matplotlib.colors import ListedColormap

# --- Setup: GT mask, GT labels, spots, color helper ---
spots_122 = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
spots_122 = spots_122[spots_122.fov == 'FOV_122'].copy().reset_index(drop=True)

_, gt, gt_mask, gt_lookup = gt_spot_labels('FOV_122', z=2)
labels_df = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_labels.csv').set_index('cell_id')
gt_cell_labels = {}
for mid, cid in gt_lookup.items():
    if cid in labels_df.index:
        row = labels_df.loc[cid]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]
        gt_cell_labels[mid] = {lvl: str(row[lvl]) for lvl in LEVELS}

def colorize_by_label(mask, cell_labels, level):
    label_per_id = {mid: lbls.get(level, 'background')
                    for mid, lbls in cell_labels.items()}
    unique_labels = ['background'] + sorted(set(label_per_id.values()) - {'background'})
    label_to_int = {lbl: i for i, lbl in enumerate(unique_labels)}
    out = np.zeros_like(mask, dtype=np.int32)
    for mid, lbl in label_per_id.items():
        out[mask == mid] = label_to_int[lbl]
    cmap = ListedColormap(
        [(0.05, 0.05, 0.05, 1.0)] +
        list(plt.cm.tab20(np.linspace(0, 1, max(len(unique_labels) - 1, 1))))
    )
    return out, cmap, unique_labels

# --- Per-cell predictions on the SAM-box mask ---
sam_counts3, sam_ids3 = spots_to_cell_counts(sam_mask, spots_122)
pred_per_cell_sam3 = knn_classifier(sam_counts3)
pred_cell_labels_sam3 = {int(cid): pred_per_cell_sam3[i] for i, cid in enumerate(sam_ids3)}
print(f'Predicted labels for {len(pred_cell_labels_sam3)} SAM-box cells')

# --- Side-by-side mask coloring at every level ---
fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    gt_img, gt_cmap, gt_lbls = colorize_by_label(gt_mask, gt_cell_labels, level)
    pr_img, pr_cmap, pr_lbls = colorize_by_label(sam_mask, pred_cell_labels_sam3, level)

    axes[0, col].imshow(gt_img, cmap=gt_cmap, interpolation='nearest')
    axes[0, col].set_title(f'GT — {level}\n({len(gt_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    axes[1, col].imshow(pr_img, cmap=pr_cmap, interpolation='nearest')
    axes[1, col].set_title(f'SAM-box+kNN — {level}\n({len(pr_lbls)-1} types)',
                            fontsize=12, pad=12,
                            bbox=dict(facecolor='white', edgecolor='none', pad=3))

    for r in range(2):
        axes[r, col].axis('off')

fig.suptitle('FOV_122 — SAM box-prompted + kNN predictions vs ground truth',
              fontsize=16, y=0.98)
plt.show()

# --- Spot-level scatter ---
pred_spot_sam3 = project_to_spots(spots_122, sam_mask, pred_cell_labels_sam3)

fig, axes = plt.subplots(2, 4, figsize=(26, 14))
plt.subplots_adjust(hspace=0.25, wspace=0.05, top=0.92, bottom=0.02)

for col, level in enumerate(LEVELS):
    for row, (labels, title) in enumerate([(gt[level], 'GT'),
                                            (pred_spot_sam3[level], 'SAM-box+kNN')]):
        unique = ['background'] + sorted(set(labels) - {'background'})
        cmap_arr = [(0.92, 0.92, 0.92, 0.4)] + [plt.cm.tab20(i % 20) for i in range(len(unique)-1)]
        lbl_to_i = {l: i for i, l in enumerate(unique)}
        c = [cmap_arr[lbl_to_i[l]] for l in labels]
        axes[row, col].scatter(spots_122['image_col'], spots_122['image_row'],
                                c=c, s=1, linewidths=0)
        axes[row, col].set_xlim(0, 2048)
        axes[row, col].set_ylim(2048, 0)
        axes[row, col].set_aspect('equal')
        axes[row, col].set_title(f'{title} — {level}',
                                  fontsize=12, pad=12,
                                  bbox=dict(facecolor='white', edgecolor='none', pad=3))
        axes[row, col].axis('off')

fig.suptitle('FOV_122 — SAM-box spot-level predictions vs ground truth',
              fontsize=16, y=0.98)
plt.show()

"""## DINOv2/DINOv3: foundation-model features → segmentation

DINOv3 is a self-supervised vision transformer with extremely strong dense
features. **It's not a segmentation model out of the box**: we extract patch
features from DAPI, cluster them, and turn the cluster map into instance masks
via connected components.

This demonstrates the "foundation features for biology" pattern.
"""

!pip install -q timm einops
import torch, torch.nn.functional as F
from PIL import Image
import torchvision.transforms as T

# Load DINOv3 from torch.hub. If unavailable in your Colab snapshot, fall back
# to DINOv2 (very similar API) — note the version.
try:
    backbone = torch.hub.load('facebookresearch/dinov3', 'dinov3_vits16')
    DINO_VER = 'v3'
except Exception:
    backbone = torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14')
    DINO_VER = 'v2 (fallback)'
backbone = backbone.to('cuda' if torch.cuda.is_available() else 'cpu').eval()
print('Using DINO', DINO_VER)

from skimage.measure import label as cc_label
from sklearn.cluster import KMeans

PATCH = 14

# Resize DAPI to a multiple of patch size; convert to 3-channel and normalize.
def dino_features(img2d, size=896):
    v = np.percentile(img2d, 99)
    x = np.clip(img2d.astype(np.float32) / max(v, 1), 0, 1).astype(np.float32)
    x = np.stack([x, x, x], axis=0)                       # (3, H, W)
    x = torch.from_numpy(x).unsqueeze(0).float()          # ensure float32
    x = F.interpolate(x, size=(size, size), mode='bilinear', align_corners=False)
    x = (x - 0.5) / 0.5
    with torch.no_grad():
        out = backbone.forward_features(x.to(next(backbone.parameters()).device))
    # 'x_norm_patchtokens' is provided by both v2 and v3
    feats = out['x_norm_patchtokens'][0]                  # (N, D)
    n = int(feats.shape[0] ** 0.5)
    return feats.cpu().numpy(), n, size

feats, n_side, size = dino_features(dapi_122, size=896)
print(f'DINO features: {feats.shape}  ({n_side}x{n_side} grid at {size}px)')

# Cluster to find a "nuclei vs background" partition.
km = KMeans(n_clusters=4, n_init=10, random_state=0).fit(feats)
cluster_map = km.labels_.reshape(n_side, n_side)

# Pick the cluster that maximally overlaps the brightest DAPI patches as 'nuclei'
dapi_small = np.array(Image.fromarray(dapi_122).resize((n_side, n_side)))
# NumPy 2.x removed ndarray.ptp(); use np.ptp() instead.
dapi_norm = (dapi_small - dapi_small.min()) / (np.ptp(dapi_small) + 1e-9)
nuc_cluster = max(range(4),
                  key=lambda c: dapi_norm[cluster_map == c].mean()
                  if (cluster_map == c).any() else -1)

nuc_small = (cluster_map == nuc_cluster).astype(np.uint8)
nuc_full = np.array(Image.fromarray(nuc_small * 255)
                    .resize((2048, 2048), Image.NEAREST)) > 0
dino_mask = cc_label(nuc_full).astype(np.int32)

fig, ax = plt.subplots(1, 3, figsize=(15, 5))
ax[0].imshow(dapi_122, cmap='gray', vmax=np.percentile(dapi_122, 99))
ax[0].set_title('DAPI')
ax[1].imshow(cluster_map, cmap='tab10')
ax[1].set_title(f'DINO{DINO_VER[0]} feature clusters')
ax[2].imshow(dino_mask, cmap='nipy_spectral')
ax[2].set_title(f'Nuclei cluster -> {dino_mask.max()} components')
for a in ax: a.axis('off')
plt.tight_layout(); plt.show()

evaluate_segmentation(f'DINO{DINO_VER[0]}+kNN', dino_mask, knn_classifier)

"""## scVI + scANVI — VAE expression embedding + semi-supervised classifier

[scvi-tools](https://scvi-tools.org/) trains a deep generative model on raw
counts and yields a denoised latent embedding. **scANVI** extends it with
cell-type labels for semi-supervised training and provides a built-in
classifier head.

We pair scANVI's classifier with the **Cellpose** mask.
```
                    ┌─────────────────────────────────────┐
                    │  Input:  x  (counts)                 │
                    │          s  (batch)                  │
                    │          y  (cell-type — partial)    │
                    └────────────┬────────────────────────┘
                                 │
                                 ▼
                       ┌────────────────────┐
                       │  scVI ENCODER → z  │   (same as above)
                       └─────────┬──────────┘
                                 │
                  ┌──────────────┴──────────────┐
                  │                             │
                  ▼                             ▼
        ┌──────────────────┐         ┌──────────────────────┐
        │  CLASSIFIER       │         │  q(u | z, y)         │
        │  q(y | z)         │         │  second latent —     │
        │  z → MLP → softmax│         │  cell-type-specific  │
        │       │           │         │  variation           │
        │       ▼           │         └──────────┬───────────┘
        │  ŷ ∈ Δ^K          │                    │
        └─────────┬─────────┘                    │
                  │                              │
        labeled cells:           unlabeled cells:│
        observe y                marginalize over y
                  │                              │
                  └──────────┬───────────────────┘
                             ▼
              ┌──────────────────────────────┐
              │   DECODER  p_θ(x | z, u, s)   │
              │   ZINB likelihood             │
              └──────────────────────────────┘

```
"""

!pip install -q scvi-tools

import anndata as ad
import scvi

adata_full = ad.read_h5ad(DATA_DIR / 'ground_truth' / 'counts.h5ad')
X = adata_full.X.toarray() if hasattr(adata_full.X, 'toarray') else np.asarray(adata_full.X)
adata_full.X = np.asarray(X, dtype=np.int32)
adata_full.obs['split'] = np.where(
    adata_full.obs.fov.isin(['FOV_160', 'FOV_107']), 'train', 'heldout')

# --- Mask held-out class labels BEFORE setup_anndata ---
if pd.api.types.is_categorical_dtype(adata_full.obs['class_label']):
    adata_full.obs['class_label'] = adata_full.obs['class_label'].cat.add_categories(['UNLABELED'])
adata_full.obs.loc[adata_full.obs['split'] == 'heldout', 'class_label'] = 'UNLABELED'

scvi.model.SCVI.setup_anndata(adata_full, batch_key='fov')
vae = scvi.model.SCVI(adata_full, n_layers=2, n_latent=20)
vae.train(max_epochs=80, early_stopping=True, accelerator='auto')

scanvi = scvi.model.SCANVI.from_scvi_model(
    vae,
    adata=adata_full,
    labels_key='class_label',
    unlabeled_category='UNLABELED',
)
scanvi.train(max_epochs=40, accelerator='auto')
print('scANVI training done')

spots_122_full = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
spots_122_full = spots_122_full[spots_122_full.fov == 'FOV_122'].copy()
cp_counts, cp_ids = spots_to_cell_counts(cp_mask, spots_122_full)

qry = ad.AnnData(
    X=cp_counts.astype(np.int32),
    obs=pd.DataFrame({
        'fov': ['FOV_122'] * len(cp_ids),
        'class_label': ['UNLABELED'] * len(cp_ids),
    }),
    var=pd.DataFrame(index=GENE_LIST),
)
pred_class = scanvi.predict(qry)
print('scANVI class predictions, head:', pred_class[:10])

assert list(qry.var_names) == list(adata_full.var_names), "Gene order mismatch!"

# If FOV_122 wasn't in scVI training, scANVI's batch encoder won't know it.
# Quick check:
print('FOV_122 in training batches?', 'FOV_122' in adata_full.obs['fov'].unique())

scanvi_models = {}
for lvl in LEVELS:
    ad_lvl = adata_full.copy()

    # Ensure 'UNLABELED' is a valid category for this level
    if isinstance(ad_lvl.obs[lvl].dtype, pd.CategoricalDtype):
        if 'UNLABELED' not in ad_lvl.obs[lvl].cat.categories:
            ad_lvl.obs[lvl] = ad_lvl.obs[lvl].cat.add_categories(['UNLABELED'])
    else:
        ad_lvl.obs[lvl] = ad_lvl.obs[lvl].astype('category').cat.add_categories(['UNLABELED'])

    ad_lvl.obs.loc[ad_lvl.obs['split'] == 'heldout', lvl] = 'UNLABELED'

    scvi.model.SCVI.setup_anndata(ad_lvl, batch_key='fov')
    v = scvi.model.SCVI(ad_lvl, n_layers=2, n_latent=20)
    v.train(max_epochs=60, early_stopping=True, accelerator='auto')
    m = scvi.model.SCANVI.from_scvi_model(
        v, adata=ad_lvl, labels_key=lvl, unlabeled_category='UNLABELED')
    m.train(max_epochs=30, accelerator='auto')
    scanvi_models[lvl] = m
    print(f'{lvl}: trained')


def scanvi_classifier(counts):
    preds_per_lvl = {}
    for lvl in LEVELS:
        q = ad.AnnData(
            X=counts.astype(np.int32),
            obs=pd.DataFrame({
                'fov': ['FOV_122'] * len(counts),
                lvl: ['UNLABELED'] * len(counts),
            }),
            var=pd.DataFrame(index=GENE_LIST),
        )
        preds_per_lvl[lvl] = scanvi_models[lvl].predict(q)
    return [{lvl: preds_per_lvl[lvl][i] for lvl in LEVELS} for i in range(len(counts))]


evaluate_segmentation('Cellpose+scANVI', cp_mask, scanvi_classifier)

"""# CellTypist (pretrained mouse-brain classifier)
[CellTypist](https://www.celltypist.org/) ships pretrained logistic-regression
models for many tissues. We try a mouse-brain model.

Caveat: CellTypist's labels follow its own taxonomy, **not** Allen Zhuang-ABCA-4.
Even so, since ARI is label-name independent, identical groupings still score.
Where labels disagree at a finer level, ARI will drop — exactly the lesson.
"""

!pip install -q celltypist

!pip install -q -U numba

import re
import celltypist
import scanpy as sc
import numpy as np, pandas as pd, anndata as ad

# --- 1. Use cortex-specific model (your data is mouse cortex) ---
MODEL_NAME = 'Mouse_Isocortex_Hippocampus.pkl'
celltypist.models.download_models(force_update=False, model=[MODEL_NAME])
ct_model = celltypist.models.Model.load(MODEL_NAME)
print(f'Using {MODEL_NAME}')

# --- 2. Build subclass → full-hierarchy lookup with MODAL supertype/cluster ---
labels_df = pd.read_csv(DATA_DIR / 'ground_truth' / 'cell_labels.csv')
labels_df = labels_df.dropna(subset=LEVELS)

sub_to_hier = {}
for sub, g in labels_df.groupby('subclass_label'):
    sub_to_hier[sub] = {
        'class_label':     g['class_label'].iloc[0],
        'subclass_label':  sub,
        'supertype_label': g['supertype_label'].mode().iloc[0],
        'cluster_label':   g['cluster_label'].mode().iloc[0],
    }
print(f'Subclass lookup has {len(sub_to_hier)} entries')

# --- 3. Build query AnnData and predict ---
spots_122_full = pd.read_csv(DATA_DIR / 'ground_truth' / 'spots_train.csv')
spots_122_full = spots_122_full[spots_122_full.fov == 'FOV_122'].copy()
cp_counts, cp_ids = spots_to_cell_counts(cp_mask, spots_122_full)

qry_ct = ad.AnnData(
    X=cp_counts.astype(np.float32),
    obs=pd.DataFrame({'fov': ['FOV_122'] * len(cp_ids)}),
    var=pd.DataFrame(index=GENE_LIST),
)

sc.pp.normalize_total(qry_ct, target_sum=1e4)
sc.pp.log1p(qry_ct)
sc.pp.pca(qry_ct, n_comps=min(30, qry_ct.n_vars - 1))
sc.pp.neighbors(qry_ct, n_neighbors=min(10, qry_ct.n_obs - 1))

ct_pred = celltypist.annotate(
    qry_ct,
    model=MODEL_NAME,
    majority_voting=True,
)
pred_labels = ct_pred.predicted_labels.iloc[:, -1].values
ct_probs = ct_pred.probability_matrix.max(axis=1).values

print(f'CellTypist unique labels predicted: {len(set(pred_labels))}')
print(f'Confidence: mean={ct_probs.mean():.2f}, '
      f'<0.5 fraction={(ct_probs < 0.5).mean()*100:.0f}%')

# --- 4. Bridge CellTypist common-name labels → ABCA-4 subclass via token containment ---
def tokens(s):
    return set(re.findall(r'[A-Za-z0-9/]+', str(s)))

ct_to_subclass = {}
for ct_label in set(pred_labels):
    ct_tok = tokens(ct_label)
    if not ct_tok:
        continue
    matches = [sub for sub in sub_to_hier if ct_tok.issubset(tokens(sub))]
    if matches:
        ct_to_subclass[ct_label] = min(matches, key=len)  # most specific (shortest) match

print(f'Mapped {len(ct_to_subclass)}/{len(set(pred_labels))} CellTypist labels:')
for k, v in ct_to_subclass.items():
    print(f'  {k!r:25s} → {v!r}')

# --- 5. Project per-cell predictions through the hierarchy ---
def celltypist_classifier(counts):
    out = []
    for i in range(len(counts)):
        pred = str(pred_labels[i])
        conf = float(ct_probs[i])
        if conf < 0.3 or pred not in ct_to_subclass:
            entry = {lvl: 'background' for lvl in LEVELS}
        else:
            entry = dict(sub_to_hier[ct_to_subclass[pred]])
        out.append(entry)
    return out

evaluate_segmentation('Cellpose+CellTypist-hier', cp_mask, celltypist_classifier)

"""# Hierarchy-aware XGBoost

The host hint: the kNN baseline scores ~flat across all 4 levels because its
errors are correlated. A **top-down conditional** classifier should win at
finer levels.

Pipeline: predict `class_label`, then concatenate the predicted class as a
feature when predicting `subclass_label`, and so on.
"""

import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

# Train data = the 147 labeled cells. Use log-normalized counts.
adata_full_xgb = ad.read_h5ad(DATA_DIR / 'ground_truth' / 'counts.h5ad')
X_all = adata_full_xgb.X if not hasattr(adata_full_xgb.X, 'toarray') else adata_full_xgb.X.toarray()
X_all = np.asarray(X_all, dtype=np.float32)
X_all = X_all / X_all.sum(axis=1, keepdims=True).clip(min=1) * 1e4
X_all = np.log1p(X_all)
train_idx = np.where(adata_full_xgb.obs.fov.isin(['FOV_160', 'FOV_107']).values)[0]
Xtr = X_all[train_idx]

encoders, models_h = {}, {}
prev = None
for lvl in LEVELS:
  y = adata_full_xgb.obs[lvl].values[train_idx]
  le = LabelEncoder().fit(y)
  feats = Xtr if prev is None else np.hstack([Xtr, prev])
  clf = xgb.XGBClassifier(
      n_estimators=200, max_depth=4, learning_rate=0.1,
      n_jobs=4, tree_method='hist', eval_metric='mlogloss',
  )
  clf.fit(feats, le.transform(y))
  encoders[lvl] = le
  models_h[lvl] = clf
  prev = clf.predict_proba(feats)
  print(f'{lvl}: trained ({len(le.classes_)} classes)')

def hxgb_classifier(counts):
  x = counts.astype(np.float32)
  x = np.log1p(x / x.sum(axis=1, keepdims=True).clip(min=1) * 1e4)
  out_per_level, prev = {}, None
  for lvl in LEVELS:
      feats = x if prev is None else np.hstack([x, prev])
      pred = models_h[lvl].predict(feats)
      out_per_level[lvl] = encoders[lvl].inverse_transform(pred)
      prev = models_h[lvl].predict_proba(feats)
  return [{lvl: out_per_level[lvl][i] for lvl in LEVELS} for i in range(len(x))]

evaluate_segmentation('Cellpose+HierXGB', cp_mask, hxgb_classifier)

"""# Squidpy + small GCN (spatial context)
Adds spatial context: build a per-FOV kNN graph over cell centroids, train a
2-layer GCN that takes log-normalized counts as node features and predicts
cell type. Inference uses the same per-FOV graph on Cellpose-detected cells.
"""

!pip install -q squidpy torch-geometric

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.data import Data
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import LabelEncoder
from skimage.measure import regionprops

device = 'cuda' if torch.cuda.is_available() else 'cpu'

def build_graph(counts, centers_xy, k=8):
    x = counts.astype(np.float32)
    x = np.log1p(x / x.sum(axis=1, keepdims=True).clip(min=1) * 1e4)
    n = len(x)
    nn_ = NearestNeighbors(n_neighbors=min(k+1, n)).fit(centers_xy)
    _, idx = nn_.kneighbors(centers_xy)
    src = np.repeat(np.arange(n), idx.shape[1] - 1)
    dst = idx[:, 1:].reshape(-1)
    edge_index = torch.tensor(np.stack([src, dst]), dtype=torch.long)
    return Data(x=torch.tensor(x), edge_index=edge_index)

class GCN(nn.Module):
    def __init__(self, in_dim, hidden, out_dim):
        super().__init__()
        self.c1 = GCNConv(in_dim, hidden)
        self.c2 = GCNConv(hidden, out_dim)
    def forward(self, d):
        h = F.relu(self.c1(d.x, d.edge_index))
        return self.c2(h, d.edge_index)

# Build per-FOV training graphs
adata_gcn = ad.read_h5ad(DATA_DIR / 'ground_truth' / 'counts.h5ad')
X_all_gcn = adata_gcn.X.toarray() if hasattr(adata_gcn.X, 'toarray') else np.asarray(adata_gcn.X)
X_all_gcn = np.asarray(X_all_gcn, dtype=np.float32)

train_data, train_y = [], {lvl: [] for lvl in LEVELS}
for fov in ['FOV_160', 'FOV_107']:
    rows = adata_gcn.obs.fov == fov
    Xc = X_all_gcn[rows.values]
    cxy = adata_gcn.obs.loc[rows, ['center_x', 'center_y']].values
    train_data.append(build_graph(Xc, cxy))
    for lvl in LEVELS:
        train_y[lvl].append(adata_gcn.obs[lvl].values[rows.values])

# Train one GCN per level
gcn_models, gcn_encoders = {}, {}
for lvl in LEVELS:
    y_all = np.concatenate(train_y[lvl])
    le = LabelEncoder().fit(y_all)
    gcn_encoders[lvl] = le
    offset = 0
    x_list, e_list, y_list = [], [], []
    for d, ys in zip(train_data, train_y[lvl]):
        x_list.append(d.x)
        e_list.append(d.edge_index + offset)
        y_list.append(torch.tensor(le.transform(ys), dtype=torch.long))
        offset += d.x.shape[0]
    big = Data(x=torch.cat(x_list), edge_index=torch.cat(e_list, dim=1)).to(device)
    y_big = torch.cat(y_list).to(device)
    model = GCN(big.x.shape[1], 64, len(le.classes_)).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=5e-3)
    for _ in range(150):
        model.train(); opt.zero_grad()
        loss = F.cross_entropy(model(big), y_big)
        loss.backward(); opt.step()
    gcn_models[lvl] = model
    print(f'{lvl}: GCN trained')

# Inference: build a graph from Cellpose-segmented FOV_122 cells
PIXEL = 0.109
fov_x = FOV_META.loc['FOV_122', 'fov_x']
fov_y = FOV_META.loc['FOV_122', 'fov_y']
rp = regionprops(cp_mask)
centers_122 = np.array([[p.centroid[1] * PIXEL + fov_x,
                          p.centroid[0] * PIXEL + fov_y]
                        for p in rp])
cp_id_order = np.array([p.label for p in rp])

def gcn_classifier(counts):
    # counts is in cp_id order from spots_to_cell_counts; align centers
    centers = centers_122  # (n_cp_cells_with_centers, 2)
    # Some Cellpose cells may have no spots -> spots_to_cell_counts returns
    # only cells with >0 spots. Match by length:
    centers = centers[:len(counts)]
    d = build_graph(counts, centers).to(device)
    out_per_level = {}
    for lvl in LEVELS:
        with torch.no_grad():
            logits = gcn_models[lvl](d)
        out_per_level[lvl] = gcn_encoders[lvl].inverse_transform(
            logits.argmax(1).cpu().numpy())
    return [{lvl: out_per_level[lvl][i] for lvl in LEVELS} for i in range(len(counts))]

evaluate_segmentation('Cellpose+GCN', cp_mask, gcn_classifier)





























